# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: d:/Xilinx/Projects/520/final_proj/w_second_pmod/hardware/pmod_led_w_switches/pmod_led_w_switches.srcs/sources_1/bd/design_1/ip/design_1_pmod_led_0_0/design_1_pmod_led_0_0.xci
# IP: The module: 'design_1_pmod_led_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/Xilinx/Projects/520/final_proj/w_second_pmod/hardware/pmod_led_w_switches/pmod_led_w_switches.gen/sources_1/bd/design_1/ip/design_1_pmod_led_0_0/constraints/pmod_led_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'design_1_pmod_led_0_0'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# IP: d:/Xilinx/Projects/520/final_proj/w_second_pmod/hardware/pmod_led_w_switches/pmod_led_w_switches.srcs/sources_1/bd/design_1/ip/design_1_pmod_led_0_0/design_1_pmod_led_0_0.xci
# IP: The module: 'design_1_pmod_led_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/Xilinx/Projects/520/final_proj/w_second_pmod/hardware/pmod_led_w_switches/pmod_led_w_switches.gen/sources_1/bd/design_1/ip/design_1_pmod_led_0_0/constraints/pmod_led_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'design_1_pmod_led_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet
